### ISSUE TITLE
Anikiety/Głosowania w reakcjach

### ISSUE THREAD

**Issue by TheAresjej** [Aquerr/PandoBot#1]
- **Komenda:** !ankieta

- **Przykład:** !ankieta (Zróbmy team do counterstrike'a!) (super pomysł!) (spoko) (głupi pomysł nie zgadzam się)

- **Zasada działania:** !ankieta (nazwa ankiety) (reakcja A) (reakcja B) (reakcja C)

![image](https://user-images.githubusercontent.com/19390797/44541959-db44d400-a70b-11e8-81a3-bbb94df35392.png)

![image](https://user-images.githubusercontent.com/19390797/44542685-d7b24c80-a70d-11e8-89ed-c7cbf7e3c4b8.png)

![image](https://user-images.githubusercontent.com/19390797/44542817-34156c00-a70e-11e8-8f48-fb9545ccd74c.png)

![image](https://user-images.githubusercontent.com/19390797/44542877-59a27580-a70e-11e8-911a-59fad692c091.png)

**Comment by Aquerr** [comment]
Zrobione wedle wytycznych :)

![image](https://user-images.githubusercontent.com/15029008/44602198-1d8b1580-a7df-11e8-97bb-8a17867bdc66.png)
