### ISSUE TITLE
Zatwierdzenie komendy !clear

### ISSUE THREAD

**Issue by TheAresjej** [Aquerr/PandoBot#14]
- **Komenda:** !clear

- **Przykład:** 
![image](https://user-images.githubusercontent.com/19390797/46910270-c2091880-cf41-11e8-8fda-573b3041bccb.png)

- **Zasada działania:** Po wpisaniu komendy !clear pojawia się okno oczekujące na zatwierdzenie  - jeśli zostanie zatwierdzone usuwa wiadomości - jeśli nie to wiadomość znika - jeśli nie dostanie reakcji znika po 10 sek.

**Comment by Aquerr** [comment]
Zrobione
