### ISSUE TITLE
Kolory okien powiadomień

### ISSUE THREAD

**Issue by TheAresjej** [Aquerr/PandoBot#16]
- **Domyślny**: #83C0A9
- **Uwaga**: #FFCC4D
- **Błąd**: #BE1931

![image](https://user-images.githubusercontent.com/19390797/46910498-c5060800-cf45-11e8-8227-e047b148b12f.png)

**Comment by TheAresjej** [comment]
**embed=discord.Embed(color=0xffcc4d)**
https://cog-creators.github.io/discord-embed-sandbox

**Comment by Aquerr** [comment]
Link spoko, ale kod to nie ten język xD

**Comment by TheAresjej** [comment]
Tak ale komenda może się chyba przydać 🤔

**Comment by Aquerr** [comment]
Ani trochę xd Panda jest w Javie 😝

**Comment by TheAresjej** [comment]
Dobra to przynajmniej wiemy że da się to zrobić 🤣

**Comment by Aquerr** [comment]
Zrobione
