### ISSUE TITLE
Komenda !opis nie działa

### ISSUE THREAD

**Issue by TheAresjej** [Aquerr/PandoBot#17]
Po wpisaniu komendy bot nie zmienia opisu. 😞 
![image](https://user-images.githubusercontent.com/19390797/48263793-a18c8b00-e427-11e8-8923-f5490d449f25.png)
![image](https://user-images.githubusercontent.com/19390797/48263796-a4877b80-e427-11e8-8917-560c244d2b67.png)

**Comment by Aquerr** [comment]
A to nie było przypadkiem !game lub !gra?

**Comment by TheAresjej** [comment]
Wcześniej była chyba komenda !game ale miała być zmieniona na !opis 😄

**Comment by TheAresjej** [comment]
komenda !game i !gra też nie działają 😞

**Comment by Aquerr** [comment]
Komenda !gra już działa

**Comment by TheAresjej** [comment]
Super tylko komenda **!gra** miała być zmieniona na **!opis** 🙄
