### ISSUE TITLE
Powiadomienie dot. ankiety zlewa się ze sobą

### ISSUE THREAD

**Issue by TheAresjej** [Aquerr/PandoBot#18]
Aktualnie:
![image](https://user-images.githubusercontent.com/19390797/48263986-414a1900-e428-11e8-84bd-c0a3b0816690.png)

Po zmianach:
![image](https://user-images.githubusercontent.com/19390797/48264107-abfb5480-e428-11e8-9371-d1b11ec3686f.png)

**Comment by Aquerr** [comment]
Prawdopodobnie naprawione

**Comment by TheAresjej** [comment]
Działa!
![image](https://user-images.githubusercontent.com/19390797/48307543-b8c69800-e54f-11e8-8f76-2647b6d92b4f.png)
