### ISSUE TITLE
Powiadomienie dot. gifów nie jest w ramce

### ISSUE THREAD

**Issue by TheAresjej** [Aquerr/PandoBot#19]
![image](https://user-images.githubusercontent.com/19390797/48264235-157b6300-e429-11e8-8586-547a43e4157c.png)

**Comment by Aquerr** [comment]
Nikt nie mówił że miało być 😝 się zrobi

**Comment by TheAresjej** [comment]
Wszystko ma być spójne 😜

**Comment by Aquerr** [comment]
Zrobione
