### ISSUE TITLE
Usuwanie ostatnich wiadomości

### ISSUE THREAD

**Issue by TheAresjej** [Aquerr/PandoBot#2]
- **Komenda:** !clear

- **Przykład:** !clear 333

- **Zasada działania:** !clear (liczba wiadomości do usunięcia)

**Comment by Aquerr** [comment]
Własnie sam o tym dzisiaj myślałem.

**Comment by TheAresjej** [comment]
Do tego można później dodać komendę typu !wyczyść która będzie robić dokładnie to samo ale przynajmniej będzie spójna językowo.

**Comment by Aquerr** [comment]
Uznajemy za zrobione? Czy dodać jeszcze te angielską wersję?

**Comment by TheAresjej** [comment]
jeśli nie trzeba z tym jakoś przesadnie kombinować to możesz dodać angielską wersje

**Comment by Aquerr** [comment]
Dodane obie wersje. Można uznać za skończone.
