### ISSUE TITLE
Wznowienie projektu

### ISSUE THREAD

**Issue by TheAresjej** [Aquerr/PandoBot#20]
Co myślisz o wznowieniu tego projektu? 😋

**Comment by Aquerr** [comment]
O Panie! Ciężkie czasy nastały. Nie ma nic za darmo. Poza tym dużo innych rzeczy mam na głowie. :stuck_out_tongue:

**Comment by TheAresjej** [comment]
Jedyna forma płatności jaka przychodzi mi do głowy to przerobienie bota w taki sposób żeby był także dostępny w wersji na inne serwery z opcją premium ale pewnie z tym też by było dużo roboty tak więc chyba aktualnie pozostaje zostawić ten pomysł. 😜
