### ISSUE TITLE
Niestandardowe akcje pandy

### ISSUE THREAD

**Issue by TheAresjej** [Aquerr/PandoBot#4]
Aktualnie panda "gra o bambus" ale można to rozwinąć i ustalić że o danej godzinie zmienia "czynność"
![image](https://user-images.githubusercontent.com/19390797/44620159-cee98400-a88f-11e8-906c-099040d453ef.png)

**Comment by Aquerr** [comment]
Z tego co sprawdzałem to nie ma opcji zmiany czynności po wystartowaniu bota, ale jeszcze popatrzę i dam znać.

**Comment by TheAresjej** [comment]
Aktualnie zostańmy przy "grze o bambus" 😉

**Comment by Aquerr** [comment]
Od 8:00 do 22:00 gra o bambus a potem jest „VTEAM”. Mam to wywalić?
