### ISSUE TITLE
Spis komend (!pomoc)

### ISSUE THREAD

**Issue by TheAresjej** [Aquerr/PandoBot#7]
- **Komenda:** !pomoc

- **Zasada działania:** Wyświetla spis dostępnych komend.

**Comment by TheAresjej** [comment]
**Yggdrasil**
--deathbattle [nick]

**Rythm**
!play [nazwa] lub !play [link do yt]
!skip 
!repeat

**Comment by TheAresjej** [comment]
A wait przecież to już jest 🤦‍♀️  trzeba to tylko trochę dopracować
![image](https://user-images.githubusercontent.com/19390797/45643774-24463900-babc-11e8-9b6d-cba98159eb4b.png)

**Comment by TheAresjej** [comment]
Dopisać #13

**Comment by TheAresjej** [comment]
![image](https://user-images.githubusercontent.com/19390797/48263330-02b35f00-e426-11e8-8225-6243218e1d74.png)
Zmieńmy to na - **Dostępne komendy:**

**Comment by TheAresjej** [comment]
Powinno być komend 😄 
![image](https://user-images.githubusercontent.com/19390797/48263913-f9c38d00-e427-11e8-9658-e3c11581a22c.png)

**Comment by TheAresjej** [comment]
Zgodnie z opisem _readme.md_ dodać komendę **!autorzy**

**Comment by Aquerr** [comment]
Chyba !autor XD
