### ISSUE TITLE
Nazwa ankiety nie mieści się w oknie

### ISSUE THREAD

**Issue by TheAresjej** [Aquerr/PandoBot#8]
![image](https://user-images.githubusercontent.com/19390797/45704696-e870a980-bb77-11e8-890d-0326c8e4be1e.png)

**Comment by Aquerr** [comment]
Bot nie wie jak poradzić sobie z tym słowem więc wypisuje go cały czas.
Jak dodasz spacje gdziekolwiek to będzie wiedział że to dwa różne słowa i wtedy drugie słowo da na linijce niżej.

Nic z tym nie zrobię, a liczenie liter to raczej coś czego chciałbym uniknąć. 
Poza tym chyba nikt nie będzie używał słów, które mają 50 liter? 😛
